# Generated by Django 3.1.6 on 2021-02-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='sellers',
            field=models.ManyToManyField(to='main_app.Seller'),
        ),
    ]
